package com.resvera.model

import java.math.BigDecimal
import java.util.UUID

/**
 * Represents a limit order in the order book.
 *
 * @param id Unique identifier (auto-generated by default)
 * @param side BUY or SELL
 * @param price Limit price
 * @param quantity Order quantity
 * @param currencyPair e.g., BTCZAR
 */
data class Order(
    val id: String = UUID.randomUUID().toString(),
    val side: OrderSide,
    val price: BigDecimal,
    val quantity: BigDecimal,
    val currencyPair: String
)
